(in-package #:plotsvn)

(defun commits-total (logentries argv)
  (declare (ignore argv))
  (cgn:set-title "Commits total")

  (let ((authors (make-hash-table :test 'equal))
        (lines)
        (max 0))
    (build-authors logentries authors)
    (maphash #'(lambda (author datemap)
                 (let ((total 0))
                   (maphash #'(lambda (date count)
                                (declare (ignore date))
                                (setf total (+ total count)))
                            datemap)
                   (push (list total author) lines)
                   (when (> total max)
                     (setf max total))))
             authors)
    (ct/set-gnuplot-options max)
    (plot-file lines)
    (cgn:format-gnuplot (format nil "plot '~a' using 2:xticlabels(1) with boxes" *plot-file*))))

(defun ct/set-gnuplot-options (max)
  (cgn:format-gnuplot (format nil "set yrange [0:~d]" max))
  (cgn:format-gnuplot "unset key")
  (cgn:format-gnuplot "set style data histogram")
  (cgn:format-gnuplot "set style fill solid border")
  (cgn:format-gnuplot "set boxwidth 0.6 relative"))
